version: '2'
services:
    db:
      ports:
        - '32350:3306'
      volumes:
        - 'magento-db:/var/lib/mysql'
        - '.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        - '.docker-custom/mysql/custom.my.cnf:/etc/mysql/conf.d/custom.my.cnf'

    fpm:
      volumes:
        - 'magento-sync:/app'
        - './php.ini:/usr/local/etc/php/conf.d/zz-php.ini'
        - './mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini'
        - './mhsendmail_linux_amd64:/usr/local/bin/mhsendmail'

    mailhog:
      image: mailhog/mailhog
      networks:
        - magento
      ports:
        - '1025:1025'
        - '8099:8025'
